export enum SpinState {
    NOT_SPINNING = "NOT_SPINNING",
    SPINNING = "SPINNING",
    DOUBLING = "DOUBLING",
    DOUBLING_END = "DOUBLING_END",
    WAITING_FOR_DOUBLING_RESULT = "WAITING_FOR_DOUBLING_RESULT",
    SHOWING_DOUBLING_RESULT = "SHOWING_DOUBLING_RESULT"
}
